import { defineConfig, type OverrideOutput } from 'orval';

const createHeader: OverrideOutput['header'] = (info) => [
  'Generated by Orval 🍺',
  'Do not edit manually.',
  ...(info.title ? [info.title] : []),
  ...(info.description ? [info.description] : []),
  ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
];

const INPUT_FILE = './openapi.yaml';
const OUTPUT_DIR = './src/libs/generated';

export default defineConfig({
  fether: {
    input: INPUT_FILE,
    output: {
      target: `${OUTPUT_DIR}/clients`,
      namingConvention: 'kebab-case',
      mode: 'tags',
      client: 'fetch',
      mock: true,
      baseUrl: 'https://frontend-engineer-codecheck-api.mirai.yumemi.io/',
      clean: true,
      biome: true,
      override: {
        header: createHeader,
      },
    },
    hooks: {
      // Add orval-disable and ts-nocheck to the top of each generated file
      afterAllFilesWrite: async (files) => {
        const fs = await import('node:fs/promises');
        const header =
          '// oxlint-disable-next-line ban-ts-comment\n// @ts-nocheck\n\n';

        for (const file of files) {
          const content = await fs.readFile(file, 'utf-8');
          if (!content.startsWith('// oxlint-disable-next-line')) {
            await fs.writeFile(file, header + content, 'utf-8');
          }
        }
      },
    },
  },
});
