import './globals.css';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { MswProvider } from '../libs/msw/MswProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <MswProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </MswProvider>
      </body>
    </html>
  );
}
